"""Generate Postgres GRANT/REVOKE + SECURITY LABEL DDL from the classification config."""

from __future__ import annotations

from datetime import datetime

from src.classifier.loader import DataClassificationConfig


def generate_grant_statements(config: DataClassificationConfig) -> str:
    """GRANT SELECT to allowed roles per table; REVOKE base access for restricted cols.

    Restricted columns are removed from the base grant: access is only available
    through the masked views (which exclude them) or to hr_partner_role / legal_role.
    """
    lines: list[str] = []
    for table, tbl in config.tables.items():
        restricted = [c for c, cfg in tbl.columns.items() if cfg.sensitivity == "restricted"]
        # Roles that may read non-restricted columns of this table.
        base_roles = sorted(
            set(config.allowed_roles("public"))
            | set(config.allowed_roles("internal"))
        )
        lines.append(f"-- {table}")
        for role in base_roles:
            lines.append(f"GRANT SELECT ON {table} TO {role};")

        if restricted:
            # Revoke broad access; restricted columns reachable only via privileged roles.
            for role in base_roles:
                lines.append(f"REVOKE SELECT ON {table} FROM {role};")
            for role in config.allowed_roles("restricted"):
                lines.append(f"GRANT SELECT ON {table} TO {role};")
            # Re-grant the safe (non-restricted) columns to base roles explicitly.
            safe_cols = [c for c in tbl.columns if c not in restricted]
            col_list = ", ".join(safe_cols)
            for role in base_roles:
                lines.append(f"GRANT SELECT ({col_list}) ON {table} TO {role};")
        lines.append("")
    return "\n".join(lines)


def generate_security_labels(config: DataClassificationConfig) -> str:
    """Emit SECURITY LABEL statements for every pii=True column."""
    lines: list[str] = []
    for table, tbl in config.tables.items():
        for col, cfg in tbl.columns.items():
            if cfg.pii:
                mask = cfg.mask_with or "NULL"
                lines.append(
                    f"SECURITY LABEL FOR anon ON COLUMN {table}.{col} "
                    f"IS 'MASKED WITH VALUE {mask}';"
                )
    return "\n".join(lines)


def generate_all_ddl(config: DataClassificationConfig) -> str:
    """Combine grants + security labels into one timestamped executable script."""
    header = (
        "-- AUTO-GENERATED by governance/src/codegen/ddl_generator.py\n"
        f"-- Generated at: {datetime.utcnow().isoformat()}Z\n"
        f"-- Config version: {config.version}\n"
        "-- Do not edit by hand; edit policies/data_classification.yml and regenerate.\n"
    )
    return "\n".join(
        [
            header,
            "-- ===== GRANT / REVOKE =====",
            generate_grant_statements(config),
            "-- ===== SECURITY LABELS (PII) =====",
            generate_security_labels(config),
            "",
        ]
    )
