"""Generate Postgres GRANT/REVOKE + SECURITY LABEL DDL from the classification config."""

from __future__ import annotations

from datetime import datetime

from src.classifier.loader import DataClassificationConfig


def generate_grant_statements(config: DataClassificationConfig) -> str:
    """GRANT SELECT to allowed roles per table; REVOKE base access for restricted cols.

    Restricted columns are removed from the base grant: access is only available
    through the masked views (which exclude them) or to hr_partner_role / legal_role.
    """
    lines: list[str] = []
    for table, tbl in config.tables.items():
        restricted = [c for c, cfg in tbl.columns.items() if cfg.sensitivity == "restricted"]
        # Roles that may read non-restricted columns of this table.
        base_roles = sorted(
            set(config.allowed_roles("public"))
            | set(config.allowed_roles("internal"))
        )
        lines.append(f"-- {table}")
        for role in base_roles:
            lines.append(f"GRANT SELECT ON {table} TO {role};")

        if restricted:
            # Revoke broad access; restricted columns reachable only via privileged roles.
            for role in base_roles:
                lines.append(f"REVOKE SELECT ON {table} FROM {role};")
            for role in config.allowed_roles("restricted"):
                lines.append(f"GRANT SELECT ON {table} TO {role};")
            # Re-grant the safe (non-restricted) columns to base roles explicitly.
            safe_cols = [c for c in tbl.columns if c not in restricted]
            col_list = ", ".join(safe_cols)
            for role in base_roles:
                lines.append(f"GRANT SELECT ({col_list}) ON {table} TO {role};")
        lines.append("")
    return "\n".join(lines)


def generate_security_labels(config: DataClassificationConfig) -> str:
    """Emit SECURITY LABEL statements for every pii=True column."""
    lines: list[str] = []
    for table, tbl in config.tables.items():
        for col, cfg in tbl.columns.items():
            if cfg.pii:
                mask = cfg.mask_with or "NULL"
                # The mask expression is embedded inside a single-quoted label string,
                # so any single quotes in it (e.g. '***') must be doubled or psql
                # rejects the statement as invalid SQL.
                label = f"MASKED WITH VALUE {mask}".replace("'", "''")
                lines.append(
                    f"SECURITY LABEL FOR anon ON COLUMN {table}.{col} IS '{label}';"
                )
    return "\n".join(lines)


def _header(config: DataClassificationConfig, *, extra: str = "") -> str:
    return (
        "-- AUTO-GENERATED by governance/src/codegen/ddl_generator.py\n"
        f"-- Generated at: {datetime.utcnow().isoformat()}Z\n"
        f"-- Config version: {config.version}\n"
        "-- Do not edit by hand; edit policies/data_classification.yml and regenerate.\n"
        f"{extra}"
    )


def generate_all_ddl(config: DataClassificationConfig) -> str:
    """Timestamped GRANT/REVOKE access-control script.

    Contains only grants/revokes so it applies against a stock Postgres with no
    extra extensions. SECURITY LABELs are emitted separately (they require the
    PostgreSQL Anonymizer extension) via :func:`generate_security_labels_script`.
    """
    return "\n".join(
        [
            _header(config),
            "-- ===== GRANT / REVOKE =====",
            generate_grant_statements(config),
            "",
        ]
    )


def generate_security_labels_script(config: DataClassificationConfig) -> str:
    """Standalone SECURITY LABEL script for PII columns.

    Requires the PostgreSQL Anonymizer ('anon') extension to be installed and
    loaded. Kept out of the core access-control script so that ``make apply-ddl``
    succeeds on a stock Postgres; apply this separately with
    ``make apply-security-labels`` once ``anon`` is available.
    """
    extra = (
        "-- Requires the PostgreSQL Anonymizer extension (CREATE EXTENSION anon;).\n"
        "-- Apply with: make apply-security-labels\n"
    )
    return "\n".join(
        [
            _header(config, extra=extra),
            "-- ===== SECURITY LABELS (PII) =====",
            generate_security_labels(config),
            "",
        ]
    )
