"""Generate column-masking CREATE VIEW statements from the classification config."""

from __future__ import annotations

from datetime import datetime

from src.classifier.loader import DataClassificationConfig, TableClassification

# Map a fully-qualified table to its generated safe-view name.
_VIEW_NAMES = {
    "analytics.dim_employees": "analytics.v_employees_safe",
    "analytics.fct_attrition_monthly": "analytics.v_attrition_safe",
    "llm.feedback": "llm.v_feedback_safe",
}


def _safe_view_name(table_fqn: str) -> str:
    if table_fqn in _VIEW_NAMES:
        return _VIEW_NAMES[table_fqn]
    schema, _, name = table_fqn.partition(".")
    return f"{schema}.v_{name}_safe"


def generate_masked_view(
    table_fqn: str,
    table_config: TableClassification,
    caller_role: str = "analyst_reader",
) -> str:
    """Build a CREATE OR REPLACE VIEW that masks confidential and drops restricted columns."""
    select_lines: list[str] = []
    for col, cfg in table_config.columns.items():
        if cfg.sensitivity in ("public", "internal"):
            select_lines.append(f"    {col}")
        elif cfg.sensitivity == "confidential":
            expr = cfg.mask_with or "NULL"
            select_lines.append(f"    -- {col}: MASKED ({'PII' if cfg.pii else 'confidential'})")
            select_lines.append(f"    {expr} AS {col}")
        elif cfg.sensitivity == "restricted":
            select_lines.append(f"    -- {col}: EXCLUDED (restricted)")

    # Drop trailing comment-only lines from forming an invalid trailing comma.
    body_cols = [ln for ln in select_lines if not ln.strip().startswith("--")]
    select_sql = ",\n".join(body_cols)
    commentary = "\n".join(ln for ln in select_lines if ln.strip().startswith("--"))

    view_name = _safe_view_name(table_fqn)
    parts = [f"CREATE OR REPLACE VIEW {view_name} AS", "SELECT"]
    if commentary:
        parts.append(commentary)
    parts.append(select_sql)
    parts.append(f"FROM {table_fqn};")
    parts.append(f"GRANT SELECT ON {view_name} TO {caller_role};")
    return "\n".join(parts)


def generate_all_views(config: DataClassificationConfig) -> str:
    """Generate masked views for every table that has confidential/restricted columns."""
    header = (
        "-- AUTO-GENERATED by governance/src/codegen/view_generator.py\n"
        f"-- Generated at: {datetime.utcnow().isoformat()}Z\n"
        f"-- Config version: {config.version}\n"
    )
    blocks = [header]
    for table, tbl in config.tables.items():
        needs_view = any(
            cfg.sensitivity in ("confidential", "restricted")
            for cfg in tbl.columns.values()
        )
        if needs_view:
            blocks.append(generate_masked_view(table, tbl))
            blocks.append("")
    return "\n".join(blocks)
